package fr.utbm.geochat;

public enum TCPCommandType {
	CLIENT_DECONNECTION, CONNECTION_EXIT, CLIENT_CHANNEL_CREATION, CLIENT_PRIVATE_CHANNEL_CREATION, CLIENT_JOIN_CHANNEL, CLIENT_JOIN_PRIVATE_CHANNEL, CLIENT_LEAVE_CHANNEL, NEW_CHANNEL_CREATED, DELETE_CHANNEL, UPDATE_CHANNEL, AUTH_SUCCESS, AUTH_FAIL, SEND_ALL, SEND, SERVER_DECONNECTION, SEND_USERNAME, MESSAGE_RECEIVED_FROM_SERVER, SEND_MESSAGE_TO_SERVER, SEND_FILE, FILE_REQUEST, FILE_ACCEPTED, FILE_REFUSED, FILE_RECEIVED, FILE_FAIL, WHISP, WHISP_RECEIVED_FROM_SERVER, CLIENT_REFUSED, CLIENT_ACCEPTED, SEND_LOCATION, REQUEST_LOCATION, SEND_LOCATIONS, REQUEST_PASSWORD, SERVER_EXIT, WIZZ_CLIENT, WIZZ_RECEIVED
}
